Improve variable names and logging

diff --git a/scripts/download_jbrowse b/scripts/download_jbrowse
--- a/scripts/download_jbrowse
+++ b/scripts/download_jbrowse
@@ -11,20 +11,20 @@ set -ue
 #   TAG: Version tag of the release to be fetched
 #   DIR: Directory where assets should be unpacked
 main () {
-    TAG="${1:-v2.15.4}"
-    INSTALL_DIR="${2:-.}"
-    JBROWSE_TMP=$(mktemp -dt "jbrowse-${TAG}-XXX")
+    TAG="${1}"
+    JBROWSE_INSTALL_DIR="${2}"
+    JRBOWSE_TMP_DIR=$(mktemp -dt "jbrowse-${TAG}-XXX")
 
-    if [[ -d "${INSTALL_DIR}/static" ]]; then
-	log_stderr "${INSTALL_DIR}/static already exists"
+    if [[ -d "${JBROWSE_INSTALL_DIR}/static" ]]; then
+	log_stderr "${JBROWSE_INSTALL_DIR}/static already exists. Not attempting anything."
 	return 1
     fi
 
     if command -v jbrowse > /dev/null; then
-	log_stderr "Using JBrowse CLI"
+	log_stderr "Using JBrowse CLI to fetch archive"
 	from_jbrowse_create
     else
-	log_stderr "JBrowse CLI not installed, falling back to Github API"
+	log_stderr "JBrowse CLI not installed, falling back on Github API to fetch archive"
 	from_github_api
     fi
 }
@@ -32,32 +32,32 @@ main () {
 from_github_api() {
     RELEASE_URL=https://api.github.com/repos/GMOD/jbrowse-components/releases/tags/"${TAG}"
 
-    if ! ARCHIVE_URL=$(get_jbrowse_web_url "${RELEASE_URL}"); then
+    if ! ARCHIVE_URL=$(get_archive_url "${RELEASE_URL}"); then
 	log_stderr "Could not find release based on tag: ${TAG}"
 	return 1
     fi
 
-    if ! curl -fsSLO --output-dir "${JBROWSE_TMP}" "${ARCHIVE_URL}"; then
+    if ! curl -fsSLO --output-dir "${JRBOWSE_TMP_DIR}" "${ARCHIVE_URL}"; then
 	log_stderr "Could not fetch archive at ${ARCHIVE_URL}"
 	return 1
     else
-	log_stderr "Saved JBrowse web archive in temporary directory ${JBROWSE_TMP}"
+	log_stderr "Saved JBrowse web archive in temporary directory ${JRBOWSE_TMP_DIR}"
     fi
 
-    log_stderr "Unzipping static files to ${INSTALL_DIR}"
-    mkdir -p "${INSTALL_DIR}" && unzip -o -q "${JBROWSE_TMP}/jbrowse-web-${TAG}.zip" 'static/*' -x 'static/*.map' -d "${INSTALL_DIR}"
-    find "${INSTALL_DIR}/static/js" -type f -name 'main.*.js' -execdir mv '{}' 'main.js' ';'
+    log_stderr "Unzipping static files to ${JBROWSE_INSTALL_DIR}"
+    mkdir -p "${JBROWSE_INSTALL_DIR}" && unzip -o -q "${JRBOWSE_TMP_DIR}/jbrowse-web-${TAG}.zip" 'static/*' -x 'static/*.map' -d "${JBROWSE_INSTALL_DIR}"
+    find "${JBROWSE_INSTALL_DIR}/static/js" -type f -name 'main.*.js' -execdir mv '{}' 'main.js' ';'
 }
 
 from_jbrowse_create () {
-    jbrowse create --tag="${TAG}" "${JBROWSE_TMP}"
+    jbrowse create --tag="${TAG}" "${JRBOWSE_TMP_DIR}"
     # Remove .map files and rename entrypoint
-    find "${JBROWSE_TMP}/static/js" -name '*.js.map' -exec rm '{}' '+' -o \
+    find "${JRBOWSE_TMP_DIR}/static/js" -name '*.js.map' -exec rm '{}' '+' -o \
 	 -name 'main.*.js' -execdir mv '{}' 'main.js' ';'
-    mkdir -p "${INSTALL_DIR}" && mv "${JBROWSE_TMP}/static" "${INSTALL_DIR}"
+    mkdir -p "${JBROWSE_INSTALL_DIR}" && mv "${JRBOWSE_TMP_DIR}/static" "${JBROWSE_INSTALL_DIR}"
 }
 
-get_jbrowse_web_url () {
+get_archive_url () {
     curl -fsSL "${1}" |\
 	jq -r '.assets[] |
 	select(.name | test("jbrowse-web")) |
@@ -69,16 +69,29 @@ log_stderr() {
 }
 
 cleanup() {
-    if [[ -d "${JBROWSE_TMP:-}" ]]; then
-	log_stderr "Deleting temporary directory ${JBROWSE_TMP}"
-	rm -rf "${JBROWSE_TMP}"
+    result="$?"
+    # Provide feedback depending on exit status
+    if [[ "${result}" != 0 ]]; then
+	if [[ -z "${TAG:-}" || -z "${JBROWSE_INSTALL_DIR=:-}" ]]; then
+	    log_stderr "Usage: download_jbrowse TAG INSTALL_DIR"
+	else
+	    log_stderr "Failed to install JBrowse ${TAG:-} in ${JBROWSE_INSTALL_DIR}"
+	fi
+    else
+	log_stderr "Successfully install JBrowse ${TAG:-} in ${JBROWSE_INSTALL_DIR:-}"
+    fi
+
+    # In any case, remove temporary directory
+    if [[ -d "${JRBOWSE_TMP_DIR:-}" ]]; then
+	log_stderr "Deleting temporary directory ${JRBOWSE_TMP_DIR}"
+	rm -rf "${JRBOWSE_TMP_DIR}"
     else
 	log_stderr "Nothing to cleanup"
     fi
+
 }
 
 trap cleanup EXIT
 
 main "$@"
-
 
